# This workflow will build a Java project with Maven

name: Java with Mavens 

env:
  BUILD_TECH: java_maven
  CONTINUE_ON_ERROR: false

on:
  push:
    branches: [ master,main ]
  pull_request:
    branches: [ master,main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout  
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    ######## Build - Maven ########
    
    - name: Build with Maven
      if: ${{ env.BUILD_TECH == 'java_maven' }}
      run: mvn clean install --batch-mode --update-snapshots verify
      continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
      
    ######## Upload Artifact ######
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
          name: artifact 
          path: ${{Github.workspace}}/target/*.jar
